In [34]:
import pandas as pd 
import requests
from bs4 import BeautifulSoup

In [94]:
r = requests.get("https://www.wunderground.com/history/airport/VOMM/2001/3/5/DailyHistory.html?req_city=Chennai&req_state=TN&req_statename=India&reqdb.zip=00000&reqdb.magic=245&reqdb.wmo=43278")

In [96]:
soup=BeautifulSoup(r.content,"html.parser")

In [97]:
soup.find("table").find_all("span")[2].text
soup.find("table").find_all("span")[6].text
soup.find("table").find_all("span")[9].text

'32'

In [98]:
# for body in soup("tbody"):
#        body.unwrap()
df = pd.read_html(str(soup),flavor="bs4")

In [102]:
df[0]

                                 Actual Average        Record
0           Temperature             NaN      NaN           NaN
1      Mean Temperature           28 °C        -           NaN
2       Max Temperature           34 °C    32 °C  35 °C (2009)
3       Min Temperature           23 °C    23 °C  20 °C (2008)
4   Cooling Degree Days              18      NaN           NaN
5   Growing Degree Days    33 (Base 50)      NaN           NaN
6              Moisture             NaN      NaN           NaN
7             Dew Point           21 °C      NaN           NaN
8      Average Humidity              69      NaN           NaN
9      Maximum Humidity              94      NaN           NaN
10     Minimum Humidity              52      NaN           NaN
11        Precipitation             NaN      NaN           NaN
12        Precipitation          0.0 mm   0.2 mm          - ()
13   Sea Level Pressure             NaN      NaN           NaN
14   Sea Level Pressure     1011.86 hPa      NaN           NaN
15                 Wind             NaN      NaN           NaN
16           Wind Speed      8 km/h  ()      NaN           NaN
17       Max Wind Speed         22 km/h      NaN           NaN
18       Max Gust Speed               -      NaN           NaN
19           Visibility  5.6 kilometers      NaN           NaN
20               Events             NaN      NaN           NaN

In [69]:
df[0].Actual[1].replace("\xa0°C", "")

'28'

In [123]:
import pandas as pd 
import requests
from bs4 import BeautifulSoup

def getTemp(year,month,day):
    
    data = {}
    url = "https://www.wunderground.com/history/airport/VOMM/{year}/{month}/{day}/DailyHistory.html?req_city=Chennai&req_state=TN&req_statename=India&reqdb.zip=00000&reqdb.magic=245&reqdb.wmo=43278"
    new_url = url.format(day=day, month=month, year=year)
    print(new_url)
    r = requests.get(new_url)
    soup=BeautifulSoup(r.content,"html.parser")
    df = pd.read_html(str(soup),flavor="bs4")
    if not "Actual" in df[0]:
        return None
    data["Mean Temp"] = df[0].Actual[1].replace("\xa0°C", "")
    data["Max Temp"] = df[0].Actual[2].replace("\xa0°C", "")
    data["Min Temp"] = df[0].Actual[3].replace("\xa0°C", "")
    data["Dew point (celcius)"] = df[0].Actual[7].replace("\xa0°C", "")
    data["Avg Humidity"] = df[0].Actual[8]
    data["Max Humidity"] = df[0].Actual[9]
    data["Min Humidity"] = df[0].Actual[10]
    data["Wind Spd (Km/h)"] = df[0].Actual[16].replace("\xa0km/h  ()", "")
    data["Max Wind Spd (Km/h)"] = df[0].Actual[17].replace("\xa0km/h", "")
    data["Sea pres (hPa)"] = df[0].Actual[14].replace("\xa0hPa", "")
    data["Date"] = "{day}/{month}/{year}".format(day=day,month=month,year=year)
    
    return data

In [124]:
data = getTemp(2011,5,11)
data

https://www.wunderground.com/history/airport/VOMM/2011/5/11/DailyHistory.html?req_city=Chennai&req_state=TN&req_statename=India&reqdb.zip=00000&reqdb.magic=245&reqdb.wmo=43278

{'Avg Humidity': '65',
 'Date': '11/5/2011',
 'Dew point (celcius)': '24',
 'Max Humidity': '89',
 'Max Temp': '40',
 'Max Wind Spd (Km/h)': '24',
 'Mean Temp': '33',
 'Min Humidity': '21',
 'Min Temp': '26',
 'Sea pres (hPa)': '1005.09',
 'Wind Spd (Km/h)': '14'}

In [125]:
from dateutil import parser, rrule

start_date = "2018-02-01"
end_date = "2018-02-03"
start = parser.parse(start_date)
end = parser.parse(end_date)
dates = list(rrule.rrule(rrule.DAILY, dtstart=start, until=end))

data = []
for d in dates:
    t = getTemp(d.year,d.month,d.day)
    data.append(t)
pd.DataFrame(data).set_index("Date")

https://www.wunderground.com/history/airport/VOMM/2018/2/1/DailyHistory.html?req_city=Chennai&req_state=TN&req_statename=India&reqdb.zip=00000&reqdb.magic=245&reqdb.wmo=43278
https://www.wunderground.com/history/airport/VOMM/2018/2/2/DailyHistory.html?req_city=Chennai&req_state=TN&req_statename=India&reqdb.zip=00000&reqdb.magic=245&reqdb.wmo=43278
https://www.wunderground.com/history/airport/VOMM/2018/2/3/DailyHistory.html?req_city=Chennai&req_state=TN&req_statename=India&reqdb.zip=00000&reqdb.magic=245&reqdb.wmo=43278

,Avg Humidity,Dew point (celcius),Max Humidity,Max Temp,Max Wind Spd (Km/h),Mean Temp,Min Humidity,Min Temp,Sea pres (hPa),Wind Spd (Km/h)
Date,,,,,,,,,,
1/2/2018,68,18,94,31,15,24,33,17,1014.17,4
2/2/2018,67,18,94,32,18,24,26,17,1013.21,6
3/2/2018,64,17,94,30,18,24,33,17,1013.67,6